paths:
  base_network: "data/raw/elec_s_37.nc"
  gtoe_csv: "data/raw/gtoe_electricity.csv"
  rescaled_network: "data/interim/network_rescaled.nc"
  expanded_network: "data/interim/network_expansion.nc"
  network_with_storage: "data/interim/network_storage.nc"
  costed_network: "data/interim/network_costed.nc"
  costs_csv: "data/raw/generator_costs.csv"   
  storage_costs_csv: "data/raw/storage_costs.csv"  
  tables_dir: "results/tables"

parameters:
  preprocess:
    bypass: true
  gtoe_to_twh: 11.63   # 1 Gtoe = 11.63 TWh
  storage:
    add_battery: true
    add_hydrogen: true
  renewables:
    keep_existing: true
  expansion:
    lines:
      enable: true
      absolute_max: 1e6
      min_equals_current: true
    links:
      enable: true
      absolute_max: 1e6
      min_equals_current: true
  co2_reductions: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.93,0.96,0.99,1]
  solve:
    solver: "gurobi"
    solver_options:
      Method: 1
      Presolve: 2
      NumericFocus: 2
      PreSparsify: 1
      ScaleFlag: -1
      FeasibilityTol: 1e-6
      OptimalityTol: 1e-6
      LogFile: "gurobi_solver.log"
logging:
  level: "INFO"

