paths:
  base_network: "data/raw/elec_s_37.nc"
  gtoe_csv: "data/raw/gtoe_electricity.csv"
  rescaled_network: "data/interim/network_rescaled.nc"
  expanded_network: "data/interim/network_expansion.nc"
  network_with_storage: "data/interim/network_storage.nc"
  costed_network: "data/interim/network_costed.nc"
  costs_csv: "data/raw/generator_costs.csv"   
  storage_costs_csv: "data/raw/storage_costs.csv"  
  tables_dir: "results/tables"

parameters:
  preprocess:
    bypass: false
  gtoe_to_twh: 11.63
  storage:
    add_battery: false
    add_hydrogen: false
  renewables:
    keep_existing: true
  expansion:
    lines:
      enable: true
      absolute_max: 200000
      min_equals_current: true
    links:
      enable: true
      absolute_max: 20000
      min_equals_current: true
    generators:
      enable: true
      # cap ALL generators of these carriers (not just extendable ones)
      only_extendable: false
      # keep existing capacity from being reduced (optional, but usually sensible)
      min_equals_current: true
      absolute_max_by_carrier:
        biomass: 36000   # MW
        nuclear: 64000   # MW
  co2_reductions: [0]
  solve:
    solver: "gurobi"
    solver_options:
      Threads: 4
      Method: 2
      Crossover: 0
      BarConvTol: 1e-5
      NodefileStart: 0.5
      MemLimit: 80000
      Presolve: 2
      NumericFocus: 3
      AggFill: 0
      ScaleFlag: 2
      LogFile: "gurobi_solver.log"


